// <auto-generated />
namespace TentsNTrails.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class fix41515 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix41515));
        
        string IMigrationMetadata.Id
        {
            get { return "201504151541399_fix4.15.15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
